name: Push to DockerHub 

on:
  workflow_dispatch:

env:
  DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
  DOCKERHUB_PASS:  ${{ secrets.DOCKERHUB_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DockerHub login 
        run: docker login -u $DOCKERHUB_USR -p $DOCKERHUB_PASS

      - name: Push to DockerHub 
        run: |
          docker build -t officialmanishkr98/maven .
          docker push officialmanishkr98/maven
          echo "-------------------Docker Image Pushed Successfully-------------------"

      - name: DockerHub logout 
        run: docker logout

