name: Push to DockerHub 

on:
  push:
# on:
#   workflow_dispatch:


  # DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  # DOCKER_IMAGE: officialmanishkr98/maven
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USR }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}
          
      - name: Push to DockerHub 
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"text" : "Randome message from CURL frm github actions"}' 'https://chat.googleapis.com/v1/spaces/AAAAN3kpaY0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=LkHQdZXVT4yN2IQj7kjSrcH1z4JLZt9e7_IDQBlXjlY'

