name: Push to DockerHub 

on:
  push:
# on:
#   workflow_dispatch:

env:
  DOCKERHUB_USR: officialmanishkr98/maven
  DOCKERHUB_PASS:  ${{ secrets.DOCKERHUB_PASS }}
  # DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  # DOCKER_IMAGE: officialmanishkr98/maven
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to DockerHub 
        run: |
          # echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USR --password-stdin
          docker login -u $DOCKERHUB_USR -p $DOCKERHUB_PASS
          docker build -t officialmanishkr98/maven .
          docker push officialmanishkr98/maven
          echo "done"

