name: Push to DockerHub 

on:
  push:
# on:
#   workflow_dispatch:


  # DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  # DOCKER_IMAGE: officialmanishkr98/maven
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DockerHub login 
        env:
          DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASS:  ${{ secrets.DOCKERHUB_PASS }}
        run: |
          export DOCKER_BUILDKIT=1
          echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USR --password-stdin
          
      - name: Push to DockerHub 
        run: |
          docker build -t officialmanishkr98/maven .
          docker push officialmanishkr98/maven
          echo "done"

