name: Push to DockerHub 

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          
      - name: Push to DockerHub 
        run: |
          docker build -t officialmanishkr98/maven .
          docker push officialmanishkr98/maven
          echo "done"

