name: Push to DockerHub 

on:
  push:
# on:
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to DockerHub 
        run: |
          ls ./
          docker run hello-world

