name: Push to DockerHub 

on:
  push:
# on:
#   workflow_dispatch:


  # DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  # DOCKER_IMAGE: officialmanishkr98/maven
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          
      - name: Push to DockerHub 
        run: |
          docker build -t officialmanishkr98/maven .
          docker push officialmanishkr98/maven
          echo "done"

