name: Push to DockerHub 

on:
  push:
# on:
#   workflow_dispatch:

env:
  DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
  DOCKERHUB_PASS:  ${{ secrets.DOCKERHUB_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: testing
        run: |
          TEST="test variable"
          echo $TEST
          echo $DOCKERHUB_USR
          echo ${{ secrets.DOCKERHUB_USR }}

      # - name: DockerHub login 
      #   run: |
      #     docker login -u $DOCKERHUB_USR -p $DOCKERHUB_PASS

      # - name: Push to DockerHub 
      #   run: |
      #     docker build -t officialmanishkr98/maven .
      #     docker push officialmanishkr98/maven
      #     echo "done"

